name: example
publish_to: none

environment:
  sdk: '>=2.19.0-0.dev <3.0.0'

flutter:
  shaders:
    - shaders/sampler.frag
    - shaders/solid_color.frag
    - shaders/blank.frag

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_shaders:
    path: ../
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
